baseURL: 'https://leo3418.github.io/'

uglyurls: true # Use Jekyll-style URLs

enableGitInfo: true
enableInlineShortcodes: true

cascade:
  - _target:
      path: '/posts/drafts/**'
    draft: true

  - _target:
      path: '/collections'
    # Do not apply the 'collections.html' layout to this page
    layout: 'list'
    # Do not use the 'permalinks.section.collections' URL pattern for this page
    url: 'collections'

  - _target:
      path: '/collections{,/**}'
      kind: 'section'
    outputs:
      # Drop 'RSS'
      - 'HTML'
