baseURL: 'https://leo3418.github.io/'

uglyurls: true # Use Jekyll-style URLs

enableGitInfo: true
enableInlineShortcodes: true

cascade:
  - _target:
      path: '/collections'
    _build:
      render: 'link'
  - _target:
      path: '/posts/drafts/**'
    draft: true
