en:
  languageName: "English"
  weight: 1
  contentDir: 'content/en'
  title: "Leo3418's Personal Site"
zh:
  languageName: "简体中文"
  weight: 2
  contentDir: 'content/zh'
  title: "Leo3418 的个人网站"
  hasCJKLanguage: true
  summaryLength: 210
