follow:
  - name: "GitHub"
    params:
      icon: 'fab fa-fw fa-github'
    url: 'https://github.com/Leo3418'

navigation:
  - identifier: 'tags'
    pageRef: '/tags'
    weight: 1
  - identifier: 'categories'
    pageRef: '/categories'
    weight: 2
