follow:
  - name: "GitHub"
    params:
      icon: 'fab fa-fw fa-github'
    url: 'https://github.com/Leo3418'

navigation:
  - pageRef: '/tags'
    weight: 1
  - pageRef: '/categories'
    weight: 2
