url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title:
  en: "Leo3418's Personal Site"
  zh: "Leo3418 的个人网站"
author: "Leo"

collections_dir: "collections"
collections:
  windows-10-mobile:
    output: true

defaults:
  - # Default
    scope:
      path: ""
    values:
      layout: "page"
  - # Posts
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Leo"
  - # Images
    scope:
      path: "assets/img"
    values:
      image: true

theme: minima

plugins:
  - jekyll-polyglot

# jekyll-polyglot
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true
sass: # https://github.com/untra/polyglot/issues/107#issuecomment-598274075
  sourcemap: never
