url: "https://leo3418.github.io"
baseurl: ""
author: "Leo"

collections_dir: "collections"
collections:
  gta-online-guides:
    output: true
    permalink: /collections/:collection/:name
    sort_by: "ordinal"
  multilingual-jekyll-site:
    output: true
    permalink: /collections/:collection/:name
    sort_by: "ordinal"
  windows-10-mobile:
    output: true
    permalink: /collections/:collection/:name

# Permalink for a post
permalink: /:year/:month/:day/:title:output_ext

defaults:
  - # Default
    scope:
      path: ""
    values:
      layout: "single"
      license: "cc-by-sa-4_0"
      toc_sticky: true
  - # Top-level Pages
    scope:
      path: "pages"
    values:
      layout: "archive"
      license: false
  - # Posts
    scope:
      path: ""
      type: "posts"
    values:
      author: "Leo"
      license: "cc-by-sa-4_0"
      show_date: true
  - # Images
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "gta-online-guides"
    values:
      toc: true

exclude:
  - "README.md"
  - "theme-mod"

theme: minimal-mistakes-jekyll

# minimal-mistakes-jekyll
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Leo3418/"
tag_archive:
  type: "liquid"
  path: "/tags"
category_archive:
  type: "liquid"
  path: "/categories"
after_footer_scripts:
  - "/assets/js/main.js"

plugins:
  - jekyll-polyglot
  - jekyll-paginate-v2

# jekyll-polyglot
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization:
  - "assets/css"
  - "assets/img"
  - "assets/js"
  - "assets/res"
parallel_localization: true
sass: # https://github.com/untra/polyglot/issues/107#issuecomment-598274075
  sourcemap: never

# jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 10
  title: ":title"
  permalink: "/page:num.html"
  sort_reverse: true
