url: "https://leo3418.github.io"
baseurl: ""
author: "Leo"

collections_dir: "collections"
collections:
  gta-online-guides:
    output: true
    permalink: /collections/:collection/:name
    sort_by: "ordinal"
  multilingual-jekyll-site:
    output: true
    permalink: /collections/:collection/:name
    sort_by: "ordinal"
  windows-10-mobile:
    output: true
    permalink: /collections/:collection/:name

defaults:
  - # Default
    scope:
      path: ""
    values:
      layout: "page"
      license: "cc-by-sa-4_0"
  - # Posts
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Leo"
      license: "cc-by-sa-4_0"
  - # Images
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "gta-online-guides"
    values:
      layout: "collection-nav"
      tags: "gta-online"
  -
    scope:
      path: ""
      type: "multilingual-jekyll-site"
    values:
      layout: "collection-nav"
      tags: "jekyll"

exclude:
  - "README.md"

theme: minima

# minima
github_username: "Leo3418"

plugins:
  - jekyll-polyglot

# jekyll-polyglot
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization:
  - "assets/css"
  - "assets/img"
  - "assets/js"
  - "assets/res"
parallel_localization: true
sass: # https://github.com/untra/polyglot/issues/107#issuecomment-598274075
  sourcemap: never
