name: "Hugo Site CI"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For Hugo's '.GitInfo'
      - name: "Set up Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: "Build the site with Hugo"
        run: hugo
      - name: "Upload the site as an artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

  deploy:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: build
    concurrency:
      group: 'github-pages'
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy the site to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
